project:
  type: website
  output-dir: docs

website:
  title: "Omar Fitian"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: mner.qmd
        text: "Mini-MNER"
      - text: "Map"
        href: map.qmd
      - href: misc.qmd
        text: "Other work"
  page-footer:
      left: |
        &copy; Omar Fitian, 2025<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual