---
title: "Strings and Regular Expressions"
editor_options: 
  chunk_output_type: inline
execute:
  echo: false
  include: false
---

```{r, include = FALSE}
library(tidyverse)
library(tidytext)
library(wordcloud)
library(ggwordcloud)
```

```{r}
nyt2020 <- read_csv("Data/archive/new_york_times_stories_2020.csv")

nyt2020 <- nyt2020 |> 
  filter(str_detect(headline, "Palestin|Israel")) |> 
  mutate(
    country = str_extract(headline, "Palestin|Israel"),
    country = ifelse(str_detect(headline, "Palestin") & str_detect(headline, "Israel"), "Both", country),
    country = recode(country, Palestin = "Palestine")
  )
```

This exercise is an attempt at comparing The New York Times headlines between Palestine and Israel. The graph below shows a great difference in the amount of articles containing the words Israel/Israeli compared to Palestine/Palestinian.

```{r}
nyt2020 |> 
  count(country) |> 
  ggplot() +
  geom_bar(aes(x = country, y = n), stat = "identity") +
  labs(
    title = "Mentions of Israel/Palestine in NYT headlines in 2020",
    x = "Country",
    y = "Number of mentions",
  ) 
```
```{r}
words_nyt2020 <- nyt2020 |> 
  unnest_tokens(output = word, input = headline) |> 
  anti_join(stop_words)

words_nyt2020
```

```{r}
words_nyt2020 |> 
  group_by(country) |> 
  count(word) |> 
  summarise(
    unique = n(),
    total = sum(n)
  ) |> 
  mutate(prop_unique = unique / total,) |> 
  ggplot() +
  geom_col(aes(x = country, y = prop_unique))
```


```{r}
nyt2020 |> 
  group_by(country) |> 
  summarise(
    sd_word_count = sd(word_count)
  ) |> 
  ggplot() +
  geom_col(aes(x = country, y = sd_word_count))
```

```{r}
set.seed(42)
words_nyt2020 |> 
  group_by(country, word) |> 
  count(country, word) |> 
ggplot(
  aes(label = word, size = n)
) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 30) +
  theme_minimal() +
  facet_wrap(~country)
```


word map
quanteda
bigrams and trigram
