---
title: "Wisconsin Districts"
editor_options: 
  chunk_output_type: console
execute:
  echo: false
---

```{r, include = FALSE}
library(tidyverse)
library(fec16)
library(skimr)
library(ggplot2)
library(ggspatial)
library(sf)
print(results_house, width = Inf)
```

```{r, include = FALSE}
results_house |>
  group_by(state, district_id) |>
  summarize(N = n())
```

```{r}
district_elections <- results_house |>
  mutate(district = parse_number(district_id)) |>
  group_by(state, district) |>
  summarize(
    N = n(), 
    total_votes = sum(general_votes, na.rm = TRUE),
    d_votes = sum(ifelse(party == "DEM", general_votes, 0), na.rm = TRUE),
    r_votes = sum(ifelse(party == "REP", general_votes, 0), na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    other_votes = total_votes - d_votes - r_votes,
    r_prop = r_votes / total_votes,  
    d_prop = d_votes / total_votes,
    winner = ifelse(r_votes > d_votes, "Republican", "Democrat")
  )
wi_results <- district_elections |>
  filter(state == "WI")
wi_results |>                  
  select(-state)
```

```{r}
wi_results |>
  skim(total_votes)
```


```{r}
wi_results |>
  summarize(
    N = n(), 
    state_votes = sum(total_votes), 
    state_d = sum(d_votes), 
    state_r = sum(r_votes)
  ) |>
  mutate(
    d_prop = state_d / state_votes, 
    r_prop = state_r / state_votes
  )
```

```{r}
wi_results |>
  select(district, r_prop, d_prop, winner) |>
  arrange(desc(r_prop))
```

```{r}
districts <- st_read("Data/districts115/cb_2016_us_cd115_500k.shp")
```

```{r}
head(districts, width = Inf)
```


```{r}
wi_shp <- districts |>
  filter(STATEFP == 55)
wi_shp |>
  st_geometry() |>
  plot(col = gray.colors(nrow(wi_shp)))
```

```{r}
wi_merged <- wi_shp |>
  mutate(
    CD115FP = parse_number(CD115FP)
  ) |> 
  st_transform(4326) |>
  inner_join(wi_results, by = c("CD115FP" = "district"))
head(wi_merged, width = Inf)
```

```{r}
wi <- ggplot(data = wi_merged, aes(fill = winner)) +
  annotation_map_tile(zoom = 6, type = "osm", progress = "none") + 
  geom_sf(alpha = 0.5) +
  scale_fill_manual("Winner", values = c("blue", "red")) + 
  geom_sf_label(aes(label = CD115FP), fill = "white") + 
  theme_void()
wi
```

```{r}
wi +
  aes(fill = r_prop) + 
  scale_fill_distiller(
    "Proportion\nRepublican", 
    palette = "RdBu", 
    limits = c(0.2, 0.8)
  )
```

```{r}
library(leaflet)
pal <- colorNumeric(palette = "RdBu", domain = c(0, 1))

leaflet_wi <- leaflet(wi_merged) |>
  addTiles() |>
  addPolygons(
    weight = 1, fillOpacity = 0.7, 
    color = ~pal(1 - r_prop),
    popup = ~paste("District", CD115FP, "</br> Proportion of republican votes:", round(r_prop, 4))
  ) |>
  setView(lng = -89, lat = 45, zoom = 6)
leaflet_wi
```

